language: cpp

dist: trusty
sudo: false

compiler:
  - gcc
  - clang

script:
  - uname -a
  - $CXX --version

  - mkdir bin
  - cd bin
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG
  - cmake --build .

  - ./Test
